In [1]:
import pandas as pd

In [2]:
month1 = pd.read_csv("cyclistic_042025.csv")
month2 = pd.read_csv("cyclistic_052025.csv")
month3 = pd.read_csv("cyclistic_062025.csv")
month4 = pd.read_csv("cyclistic_072025.csv")
month5 = pd.read_csv("cyclistic_082025.csv")
month6 = pd.read_csv("cyclistic_092025.csv")
month7 = pd.read_csv("cyclistic_102025.csv")
month8 = pd.read_csv("cyclistic_112025.csv")
month9 = pd.read_csv("cyclistic_122025.csv")
month10 = pd.read_csv("cyclistic_012026.csv")
month11 = pd.read_csv("cyclistic_022026.csv")
month12 = pd.read_csv("cyclistic_032026.csv")

/var/folders/hx/dzbqjlq53lgczp8j079dlnpr0000gn/T/ipykernel_23005/2983438796.py:1: DtypeWarning: Columns (0: start_station_name, 1: start_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  month1 = pd.read_csv("cyclistic_042025.csv")
/var/folders/hx/dzbqjlq53lgczp8j079dlnpr0000gn/T/ipykernel_23005/2983438796.py:2: DtypeWarning: Columns (0: start_station_name, 1: start_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  month2 = pd.read_csv("cyclistic_052025.csv")
/var/folders/hx/dzbqjlq53lgczp8j079dlnpr0000gn/T/ipykernel_23005/2983438796.py:8: DtypeWarning: Columns (0: ride_length) have mixed types. Specify dtype option on import or set low_memory=False.
  month8 = pd.read_csv("cyclistic_112025.csv")
/var/folders/hx/dzbqjlq53lgczp8j079dlnpr0000gn/T/ipykernel_23005/2983438796.py:9: DtypeWarning: Columns (0: ride_length) have mixed types. Specify dtype option on import or set low_memory=False.
  month9 = pd.read_csv("cyclistic_122025.csv")

In [4]:
month1.info()

<class 'pandas.DataFrame'>
RangeIndex: 371341 entries, 0 to 371340
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             371341 non-null  str
 1   rideable_type       371341 non-null  str
 2   started_at          371341 non-null  str
 3   ended_at            371341 non-null  str
 4   start_station_name  300145 non-null  str
 5   start_station_id    300145 non-null  object
 6   end_station_name    297706 non-null  str
 7   end_station_id      297706 non-null  str
 8   start_lat           371341 non-null  float64
 9   start_lng           371341 non-null  float64
 10  end_lat             371052 non-null  float64
 11  end_lng             371052 non-null  float64
 12  member_casual       371341 non-null  str
 13  ride_length         371341 non-null  str
 14  day_of_week         371341 non-null  int64
dtypes: float64(4), int64(1), object(1), str(9)
memory usage: 92.7+ MB

In [5]:
all_trips = pd.concat([month1, month2, month3, month4, month5, month6, month7, month8, month9, month10, month11, month12], ignore_index=True)

In [6]:
all_trips = all_trips.drop(columns=['start_lat', 'start_lng', 'end_lat', 'end_lng'], errors='ignore')

In [7]:
all_trips.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'member_casual', 'ride_length', 'day_of_week'],
      dtype='str')

In [9]:
all_trips.info()

<class 'pandas.DataFrame'>
RangeIndex: 5620544 entries, 0 to 5620543
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             str
 1   rideable_type       str
 2   started_at          str
 3   ended_at            str
 4   start_station_name  str
 5   start_station_id    object
 6   end_station_name    str
 7   end_station_id      str
 8   member_casual       str
 9   ride_length         str
 10  day_of_week         int64
dtypes: int64(1), object(1), str(9)
memory usage: 1.2+ GB

In [10]:
print(all_trips['member_casual'].value_counts())

member_casual
member    3605045
casual    2015499
Name: count, dtype: int64

In [14]:
all_trips.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,ride_length,day_of_week
0,A9071EF8BE4108B7,electric_bike,2025-04-14 17:01:29.778 UTC,2025-04-14 17:01:39.207 UTC,NaN,NaN,NaN,NaN,member,00:00:10,2
1,B57F51FCC47E2329,electric_bike,2025-04-18 16:12:46.586 UTC,2025-04-18 19:33:45.361 UTC,NaN,NaN,NaN,NaN,casual,03:20:59,6
2,A4D65C79D79FA4C6,electric_bike,2025-04-22 06:39:36.503 UTC,2025-04-22 06:40:44.531 UTC,NaN,NaN,Public Rack - Baltimore Ave & 132nd St,584,member,00:01:08,3
3,0191C08372896591,electric_bike,2025-04-08 09:54:24.39 UTC,2025-04-08 10:07:03.6 UTC,NaN,NaN,Commercial Ave & 130th St,20213,member,00:12:39,3
4,074A485512C78468,electric_bike,2025-04-17 16:18:04.961 UTC,2025-04-17 16:43:08.841 UTC,NaN,NaN,NaN,NaN,casual,00:25:04,5

In [45]:
all_trips['ride_length'] = pd.to_timedelta(all_trips['ride_length'])

# 2. Şimdi filtrenizi tekrar uygulayabilirsiniz.
# Dikkat: 0 sayısını da pd.Timedelta(0) olarak yazıyoruz ki elma ile elmayı kıyaslayabilelim.
all_trips_v2 = all_trips[
    (all_trips['start_station_name'] != "HQ QR") &
    (all_trips['ride_length'] >= pd.Timedelta(0))
].copy()

In [46]:
all_trips_v2.groupby('member_casual')['ride_length'].agg(['mean', 'median', 'max', 'min'])

                                mean          median             max    min
member_casual
casual        0 days 00:19:44.823339 0 days 00:11:32 1 days 01:59:57 0 days
member        0 days 00:12:10.385877 0 days 00:08:40 1 days 01:59:54 0 days

In [47]:
all_trips_v2.groupby(['member_casual', 'day_of_week'])['ride_length'].mean()

member_casual  day_of_week
casual         1             0 days 00:22:44.334818
               2             0 days 00:19:58.706677
               3             0 days 00:17:16.513679
               4             0 days 00:16:32.242206
               5             0 days 00:17:21.822924
               6             0 days 00:19:13.097758
               7             0 days 00:22:08.049189
member         1             0 days 00:13:22.814114
               2             0 days 00:11:53.239384
               3             0 days 00:11:43.061642
               4             0 days 00:11:41.392504
               5             0 days 00:11:43.093762
               6             0 days 00:12:06.617242
               7             0 days 00:13:17.964543
Name: ride_length, dtype: timedelta64[us]

In [48]:
days_order = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
all_trips_v2['day_of_week'] = all_trips_v2['day_of_week'].astype(str)
all_trips_v2['day_of_week'] = all_trips_v2['day_of_week'].replace({
    1: "Sunday",
    2: "Monday",
    3: "Tuesday",
    4: "Wednesday",
    5: "Thursday",
    6: "Friday",
    7: "Saturday",
})

In [49]:
all_trips_v2.groupby(['member_casual', 'day_of_week'])['ride_length'].mean()

member_casual  day_of_week
casual         1             0 days 00:22:44.334818
               2             0 days 00:19:58.706677
               3             0 days 00:17:16.513679
               4             0 days 00:16:32.242206
               5             0 days 00:17:21.822924
               6             0 days 00:19:13.097758
               7             0 days 00:22:08.049189
member         1             0 days 00:13:22.814114
               2             0 days 00:11:53.239384
               3             0 days 00:11:43.061642
               4             0 days 00:11:41.392504
               5             0 days 00:11:43.093762
               6             0 days 00:12:06.617242
               7             0 days 00:13:17.964543
Name: ride_length, dtype: timedelta64[us]

In [50]:
summary_stats = all_trips_v2.groupby(['member_casual', 'day_of_week']).agg(
    number_of_rides=('ride_id', 'count'),
    average_duration=('ride_length', 'mean')
).reset_index()

In [51]:
counts = all_trips_v2.groupby(['member_casual', 'day_of_week'])['ride_length'].mean().reset_index()
counts.to_csv('avg_ride_length.csv', index=False)